In [1]:
import pandas as pd
vcf = pd.read_pickle("vcf_select.pkl")
c = pd.read_csv("clinical.csv").drop("Unnamed: 0", axis=1).rename(columns={"PTID":"subject"})
img = pd.read_pickle('mri_meta.pkl')[["img_array", "subject", "label"]]

In [2]:
vcf.head()

,label,subject,Group,69039,69051,69057,69063,69070,69072,69073,...,392896,392897,392899,392907,392908,392910,392911,392922,392924,392925
0,0.0,002_S_0413,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1,0.0,0.0,0.0,0.0
3,0.0,002_S_0413,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0.0,002_S_0685,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2,0.0,0.0,0.0,0.0
9,0.0,002_S_0685,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2.0,002_S_0729,2.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,1.0,1.0,0.0,1.0,4/6,0.0,0.0,0.0,2.0

In [3]:
c.head()

,subject,RID,Phase,Group,PTGENDER_-4.0,PTGENDER_1.0,PTGENDER_2.0,PTWORK_-4,PTWORK_accounting,PTWORK_admin,...,NXSENSOR_2.0,PTCOGBEG,PHC_EXF,AGE,PTADDX,PTDOBYY,PHC_VSP,EXAMDATE,PHC_LAN,PHC_MEM
0,002_S_0295,295,ADNI1,0.0,0,1,0,0,0,0,...,0,-4.0,0.554,84.9363,-4.0,1921.0,0.483,2006-04-04,0.272,1.357
1,002_S_0413,413,ADNI1,0.0,0,0,1,0,1,0,...,1,-4.0,1.480,76.9528,-4.0,1929.0,-4.000,2006-04-06,2.594,1.287
2,002_S_0559,559,ADNI1,0.0,0,1,0,0,0,0,...,0,-4.0,1.176,80.5284,-4.0,1927.0,-4.000,2006-05-11,1.041,0.768
3,002_S_0619,619,ADNI1,2.0,0,1,0,0,0,0,...,1,-4.0,-0.509,78.0315,-4.0,1928.0,0.264,2006-05-18,0.116,-1.259
4,002_S_0685,685,ADNI1,0.0,0,0,1,0,0,0,...,0,-4.0,0.111,92.7228,-4.0,1916.0,-4.000,2006-06-22,1.170,0.149

In [4]:
c = c.rename(columns = {"Group":"GROUP"})

In [5]:
a = vcf.merge(c, on = ["subject", "GROUP"]).merge(img, on = "subject")

KeyError: 'GROUP'

In [ ]:
a["subject"].value_counts()

In [ ]:
a["GROUP"].value_counts()

In [ ]:
a["GROUP"].value_counts()

In [ ]:
cols = list(set(a.columns) - set(["PTID", "label", "GROUP",
                                  "RID", "ID", "Group", "Phase", "SITEID", "VISCODE", "VISCODE2", "USERDATE", "USERDATE2", "update_stamp", "DX", "Unnamed: 0"]))

In [ ]:
X= a[cols]
y = a["GROUP"]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, stratify=y)

In [ ]:
X_test[["subject"]].to_csv("overlap_test_set.csv")

In [ ]:
snp_cols = set(X_train.columns).intersection(set(vcf.columns))

In [ ]:
X_train_snp = X_train[snp_cols]
X_test_snp = X_test[snp_cols]

In [ ]:
img_cols = set(X_train.columns).intersection(set(img.columns))
print(len(img.columns))
print(len(img_cols))
X_train_img = X_train[img_cols]
X_test_img = X_test[img_cols]

In [ ]:
clin_cols = set(X_train.columns).intersection(set(c.columns))
print(len(c.columns))
print(len(clin_cols))
X_train_clin = X_train[clin_cols]
X_test_clin = X_test[clin_cols]

In [ ]:
pd.DataFrame(X_train_snp).to_pickle("X_train_snp.pkl")
pd.DataFrame(X_test_snp).to_pickle("X_test_snp.pkl")
pd.DataFrame(y_train).to_pickle("y_train.pkl")
pd.DataFrame(y_test).to_pickle("y_test.pkl")

pd.DataFrame(X_train_clin).to_pickle("X_train_clinical.pkl")
pd.DataFrame(X_test_clin).to_pickle("X_test_clinical.pkl")

pd.DataFrame(X_train_img).to_pickle("X_train_img.pkl")
pd.DataFrame(X_test_img).to_pickle("X_test_img.pkl")

---------------------------------------------------------------------------------------------------------